POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
    "titulo": "Probando POSTMAN",
    "autor": "Juan Miercoles",
    "url": "https://miblog.com",
    "likes": "20",
    "important": true
}